"""Clinical concept mapping from verified source columns.

Fields are listed only when observed. Name similarity is not treated as
equivalence; CDE or GDC definitions are cited when available.
"""

from __future__ import annotations

from typing import Any

# Exact source columns observed in Stage 1 / Stage 2. Definitions from GDC
# mapping or TARGET CDE where inspected.
CONCEPT_SOURCES: tuple[dict[str, Any], ...] = (
    {
        "concept": "vital_status",
        "source_kind": "gdc_cases_api",
        "source_workbook": None,
        "source_sheet": None,
        "source_entity": "demographic",
        "source_column": "demographic.vital_status",
        "source_definition": (
            "The survival state of the person registered on the protocol."
        ),
        "type": "keyword",
        "units": None,
        "coding": "Alive; Dead; Not Reported; Unknown",
        "notes": "GDC restricts its own survival calculations to alive/dead.",
    },
    {
        "concept": "vital_status",
        "source_kind": "clinical_supplement",
        "source_workbook": "TARGET clinical-data workbooks",
        "source_sheet": "Clinical Data / Sheet1",
        "source_entity": "supplement_row",
        "source_column": "Vital Status",
        "source_definition": (
            "CDE: The subdivisions of responses that describe whether a person "
            "who has taken part in an activity is alive, dead or if their status "
            "is unknown or unspecified."
        ),
        "type": "categorical",
        "units": None,
        "coding": "Alive; Dead; Unknown; Unspecified",
        "notes": "Candidate equivalent to GDC vital_status pending discordance audit.",
    },
    {
        "concept": "os_time",
        "source_kind": "gdc_cases_api",
        "source_workbook": None,
        "source_sheet": None,
        "source_entity": "demographic",
        "source_column": "demographic.days_to_death",
        "source_definition": "Days between index date and date of death.",
        "type": "long",
        "units": "days",
        "coding": None,
        "notes": "Event time for Dead cases only. Not a complete OS time.",
    },
    {
        "concept": "os_time",
        "source_kind": "gdc_cases_api",
        "source_workbook": None,
        "source_sheet": None,
        "source_entity": "diagnosis",
        "source_column": "diagnoses.days_to_last_follow_up",
        "source_definition": (
            "Time interval from last follow-up to initial pathologic diagnosis, days."
        ),
        "type": "double",
        "units": "days",
        "coding": None,
        "notes": "Candidate censoring time. Not locked.",
    },
    {
        "concept": "os_time",
        "source_kind": "gdc_cases_api",
        "source_workbook": None,
        "source_sheet": None,
        "source_entity": "follow_up",
        "source_column": "follow_ups.days_to_follow_up",
        "source_definition": (
            "Days from index to last follow-up appointment or contact."
        ),
        "type": "long",
        "units": "days",
        "coding": None,
        "notes": "Multiple records per case; Last Contact vs first-event timepoints.",
    },
    {
        "concept": "os_time",
        "source_kind": "clinical_supplement",
        "source_workbook": "TARGET clinical-data workbooks",
        "source_sheet": "Clinical Data / Sheet1",
        "source_entity": "supplement_row",
        "source_column": "Overall Survival Time in Days",
        "source_definition": (
            "CDE: The number of days after diagnosis to the last follow-up or death."
        ),
        "type": "numeric",
        "units": "days",
        "coding": None,
        "notes": (
            "Single precomputed OS time. Candidate equivalent pending concordance."
        ),
    },
    {
        "concept": "age_at_diagnosis",
        "source_kind": "gdc_cases_api",
        "source_workbook": None,
        "source_sheet": None,
        "source_entity": "diagnosis",
        "source_column": "diagnoses.age_at_diagnosis",
        "source_definition": "Age at diagnosis expressed in days since birth.",
        "type": "long",
        "units": "days",
        "coding": None,
        "notes": "Preferred GDC age field from Stage 1.",
    },
    {
        "concept": "age_at_diagnosis",
        "source_kind": "clinical_supplement",
        "source_workbook": "TARGET clinical-data workbooks",
        "source_sheet": "Clinical Data / Sheet1",
        "source_entity": "supplement_row",
        "source_column": "Age at Diagnosis in Days",
        "source_definition": (
            "CDE: Patient's age in days at diagnosis (min 1, max 15000)."
        ),
        "type": "numeric",
        "units": "days",
        "coding": None,
        "notes": "Same unit as GDC age_at_diagnosis; still requires concordance.",
    },
    {
        "concept": "sex",
        "source_kind": "gdc_cases_api",
        "source_workbook": None,
        "source_sheet": None,
        "source_entity": "demographic",
        "source_column": "demographic.sex_at_birth",
        "source_definition": "A textual description of a person's sex at birth.",
        "type": "keyword",
        "units": None,
        "coding": "male; female; unknown",
        "notes": "demographic.gender is not in the current GDC mapping.",
    },
    {
        "concept": "sex",
        "source_kind": "clinical_supplement",
        "source_workbook": "TARGET clinical-data workbooks",
        "source_sheet": "Clinical Data / Sheet1",
        "source_entity": "supplement_row",
        "source_column": "Gender",
        "source_definition": (
            "CDE: Text designations that identify gender, based upon self-report."
        ),
        "type": "categorical",
        "units": None,
        "coding": "Female; Male; Unknown",
        "notes": (
            "CDE definition is gender, not sex at birth. Not declared equivalent "
            "to demographic.sex_at_birth without discordance review."
        ),
    },
    {
        "concept": "race",
        "source_kind": "gdc_cases_api",
        "source_workbook": None,
        "source_sheet": None,
        "source_entity": "demographic",
        "source_column": "demographic.race",
        "source_definition": "OMB/Census-style race grouping.",
        "type": "keyword",
        "units": None,
        "coding": None,
        "notes": "Substantial Unknown/not reported codes in Stage 1.",
    },
    {
        "concept": "race",
        "source_kind": "clinical_supplement",
        "source_workbook": "TARGET clinical-data workbooks",
        "source_sheet": "Clinical Data / Sheet1",
        "source_entity": "supplement_row",
        "source_column": "Race",
        "source_definition": None,
        "type": "categorical",
        "units": None,
        "coding": None,
        "notes": "Same concept name as GDC; coding may differ.",
    },
    {
        "concept": "ethnicity",
        "source_kind": "gdc_cases_api",
        "source_workbook": None,
        "source_sheet": None,
        "source_entity": "demographic",
        "source_column": "demographic.ethnicity",
        "source_definition": "Hispanic or Latino self-described grouping.",
        "type": "keyword",
        "units": None,
        "coding": None,
        "notes": None,
    },
    {
        "concept": "ethnicity",
        "source_kind": "clinical_supplement",
        "source_workbook": "TARGET clinical-data workbooks",
        "source_sheet": "Clinical Data / Sheet1",
        "source_entity": "supplement_row",
        "source_column": "Ethnicity",
        "source_definition": None,
        "type": "categorical",
        "units": None,
        "coding": None,
        "notes": None,
    },
    {
        "concept": "wbc_at_diagnosis",
        "source_kind": "clinical_supplement",
        "source_workbook": "TARGET clinical-data workbooks",
        "source_sheet": "Clinical Data / Sheet1",
        "source_entity": "supplement_row",
        "source_column": "WBC at Diagnosis",
        "source_definition": "CDE: absolute peripheral WBC (x10^3/mcL).",
        "type": "numeric",
        "units": "x10^3/mcL",
        "coding": None,
        "notes": "Not populated on the GDC Cases API diagnosis entity.",
    },
    {
        "concept": "risk_group",
        "source_kind": "clinical_supplement",
        "source_workbook": "TARGET clinical-data workbooks",
        "source_sheet": "Clinical Data / Sheet1",
        "source_entity": "supplement_row",
        "source_column": "Risk group",
        "source_definition": (
            "CDE: cytogenetics- and biomarker-defined AML risk "
            "(High / Low / Standard)."
        ),
        "type": "categorical",
        "units": None,
        "coding": "High Risk; Low Risk; Standard Risk",
        "notes": "GDC eln_risk_classification and calgb_risk_group were empty.",
    },
    {
        "concept": "flt3_itd",
        "source_kind": "clinical_supplement",
        "source_workbook": "TARGET clinical-data workbooks",
        "source_sheet": "Clinical Data / Sheet1",
        "source_entity": "supplement_row",
        "source_column": "FLT3/ITD positive?",
        "source_definition": "CDE: FLT3 internal tandem duplication indicator.",
        "type": "categorical",
        "units": None,
        "coding": "Yes; No; Unknown",
        "notes": "Not in populated Cases API fields.",
    },
    {
        "concept": "npm",
        "source_kind": "clinical_supplement",
        "source_workbook": "TARGET clinical-data workbooks",
        "source_sheet": "Clinical Data / Sheet1",
        "source_entity": "supplement_row",
        "source_column": "NPM mutation",
        "source_definition": None,
        "type": "categorical",
        "units": None,
        "coding": None,
        "notes": "Not in populated Cases API fields.",
    },
    {
        "concept": "cebpa",
        "source_kind": "clinical_supplement",
        "source_workbook": "TARGET clinical-data workbooks",
        "source_sheet": "Clinical Data / Sheet1",
        "source_entity": "supplement_row",
        "source_column": "CEBPA mutation",
        "source_definition": None,
        "type": "categorical",
        "units": None,
        "coding": None,
        "notes": "Not in populated Cases API fields.",
    },
    {
        "concept": "fab",
        "source_kind": "clinical_supplement",
        "source_workbook": "TARGET clinical-data workbooks",
        "source_sheet": "Clinical Data / Sheet1",
        "source_entity": "supplement_row",
        "source_column": "FAB Category",
        "source_definition": "CDE: French-American-British morphology code.",
        "type": "categorical",
        "units": None,
        "coding": "M0–M7 and related labels",
        "notes": "Completeness is file-dependent. GDC fab_morphology_code was empty.",
    },
    {
        "concept": "cns_disease",
        "source_kind": "clinical_supplement",
        "source_workbook": "TARGET clinical-data workbooks",
        "source_sheet": "Clinical Data / Sheet1",
        "source_entity": "supplement_row",
        "source_column": "CNS disease",
        "source_definition": None,
        "type": "categorical",
        "units": None,
        "coding": None,
        "notes": "Not in populated Cases API fields.",
    },
    {
        "concept": "marrow_blasts",
        "source_kind": "clinical_supplement",
        "source_workbook": "TARGET clinical-data workbooks",
        "source_sheet": "Clinical Data / Sheet1",
        "source_entity": "supplement_row",
        "source_column": "Bone marrow leukemic blast percentage (%)",
        "source_definition": (
            "CDE: percentage of blast cells among nucleated marrow cells."
        ),
        "type": "numeric",
        "units": "percent",
        "coding": None,
        "notes": None,
    },
    {
        "concept": "peripheral_blasts",
        "source_kind": "clinical_supplement",
        "source_workbook": "TARGET clinical-data workbooks",
        "source_sheet": "Clinical Data / Sheet1",
        "source_entity": "supplement_row",
        "source_column": "Peripheral blasts (%)",
        "source_definition": None,
        "type": "numeric",
        "units": "percent",
        "coding": None,
        "notes": None,
    },
    {
        "concept": "cytogenetics_t821",
        "source_kind": "clinical_supplement",
        "source_workbook": "TARGET clinical-data workbooks",
        "source_sheet": "Clinical Data / Sheet1",
        "source_entity": "supplement_row",
        "source_column": "t(8;21)",
        "source_definition": "CDE: presence of t(8;21) cytogenetic abnormality.",
        "type": "categorical",
        "units": None,
        "coding": "Yes; No; Unknown",
        "notes": "Lesion-specific indicator. Not collapsed into a composite karyotype.",
    },
    {
        "concept": "cytogenetics_inv16",
        "source_kind": "clinical_supplement",
        "source_workbook": "TARGET clinical-data workbooks",
        "source_sheet": "Clinical Data / Sheet1",
        "source_entity": "supplement_row",
        "source_column": "inv(16)",
        "source_definition": "CDE: presence of inv(16) cytogenetic abnormality.",
        "type": "categorical",
        "units": None,
        "coding": "Yes; No; Unknown",
        "notes": "Lesion-specific indicator.",
    },
    {
        "concept": "cytogenetics_mll",
        "source_kind": "clinical_supplement",
        "source_workbook": "TARGET clinical-data workbooks",
        "source_sheet": "Clinical Data / Sheet1",
        "source_entity": "supplement_row",
        "source_column": "MLL",
        "source_definition": None,
        "type": "categorical",
        "units": None,
        "coding": None,
        "notes": "Lesion-specific indicator.",
    },
    {
        "concept": "cytogenetics_monosomy7",
        "source_kind": "clinical_supplement",
        "source_workbook": "TARGET clinical-data workbooks",
        "source_sheet": "Clinical Data / Sheet1",
        "source_entity": "supplement_row",
        "source_column": "monosomy 7",
        "source_definition": None,
        "type": "categorical",
        "units": None,
        "coding": None,
        "notes": "Lesion-specific indicator.",
    },
    {
        "concept": "primary_cytogenetic_code",
        "source_kind": "clinical_supplement",
        "source_workbook": "TARGET clinical-data workbooks",
        "source_sheet": "Clinical Data / Sheet1",
        "source_entity": "supplement_row",
        "source_column": "Primary Cytogenetic Code",
        "source_definition": None,
        "type": "categorical",
        "units": None,
        "coding": None,
        "notes": "Summary cytogenetic code; not assumed equivalent to lesion flags.",
    },
)

CYTOGENETIC_COLUMNS: tuple[str, ...] = (
    "t(8;21)",
    "inv(16)",
    "MLL",
    "monosomy 7",
    "monosomy 5",
    "t(6;9)",
    "Primary Cytogenetic Code",
)
