-- Stage 4 analysis extract view.
-- Joins the frozen primary OS cohort to reconciled baseline covariates.
-- Does not reimplement identity, age eligibility, event, or censoring rules.

CREATE OR REPLACE VIEW analytics.stage4_primary_cohort_extract AS
SELECT
    c.analysis_person_id,
    c.gdc_case_id,
    c.submitter_id,
    c.age_at_diagnosis_days,
    c.age_at_diagnosis_years,
    c.vital_status,
    c.os_event,
    c.os_days,
    c.os_years,
    c.os_time_source,
    c.os_event_source,
    c.identity_rule,
    c.source_provenance,
    c.qa_flags,
    MAX(b.value) FILTER (WHERE b.concept = 'sex_at_birth') AS sex_at_birth,
    MAX(b.missingness_class) FILTER (WHERE b.concept = 'sex_at_birth') AS sex_at_birth_missingness,
    MAX(b.source_kind) FILTER (WHERE b.concept = 'sex_at_birth') AS sex_at_birth_source_kind,
    MAX(b.conflict_flag::text) FILTER (WHERE b.concept = 'sex_at_birth') AS sex_at_birth_conflict,
    MAX(b.value) FILTER (WHERE b.concept = 'race') AS race,
    MAX(b.missingness_class) FILTER (WHERE b.concept = 'race') AS race_missingness,
    MAX(b.source_kind) FILTER (WHERE b.concept = 'race') AS race_source_kind,
    MAX(b.conflict_flag::text) FILTER (WHERE b.concept = 'race') AS race_conflict,
    MAX(b.value) FILTER (WHERE b.concept = 'ethnicity') AS ethnicity,
    MAX(b.missingness_class) FILTER (WHERE b.concept = 'ethnicity') AS ethnicity_missingness,
    MAX(b.source_kind) FILTER (WHERE b.concept = 'ethnicity') AS ethnicity_source_kind,
    MAX(b.conflict_flag::text) FILTER (WHERE b.concept = 'ethnicity') AS ethnicity_conflict,
    MAX(b.value) FILTER (WHERE b.concept = 'wbc_at_diagnosis') AS wbc_at_diagnosis,
    MAX(b.missingness_class) FILTER (WHERE b.concept = 'wbc_at_diagnosis') AS wbc_at_diagnosis_missingness,
    MAX(b.source_workbook) FILTER (WHERE b.concept = 'wbc_at_diagnosis') AS wbc_at_diagnosis_source_workbook,
    MAX(b.source_kind) FILTER (WHERE b.concept = 'wbc_at_diagnosis') AS wbc_at_diagnosis_source_kind,
    MAX(b.units) FILTER (WHERE b.concept = 'wbc_at_diagnosis') AS wbc_at_diagnosis_units,
    MAX(b.conflict_flag::text) FILTER (WHERE b.concept = 'wbc_at_diagnosis') AS wbc_at_diagnosis_conflict,
    MAX(b.value) FILTER (WHERE b.concept = 'risk_group') AS risk_group,
    MAX(b.missingness_class) FILTER (WHERE b.concept = 'risk_group') AS risk_group_missingness,
    MAX(b.source_workbook) FILTER (WHERE b.concept = 'risk_group') AS risk_group_source_workbook,
    MAX(b.conflict_flag::text) FILTER (WHERE b.concept = 'risk_group') AS risk_group_conflict,
    MAX(b.value) FILTER (WHERE b.concept = 'flt3_itd') AS flt3_itd,
    MAX(b.missingness_class) FILTER (WHERE b.concept = 'flt3_itd') AS flt3_itd_missingness,
    MAX(b.source_workbook) FILTER (WHERE b.concept = 'flt3_itd') AS flt3_itd_source_workbook,
    MAX(b.conflict_flag::text) FILTER (WHERE b.concept = 'flt3_itd') AS flt3_itd_conflict,
    MAX(b.value) FILTER (WHERE b.concept = 'npm') AS npm,
    MAX(b.missingness_class) FILTER (WHERE b.concept = 'npm') AS npm_missingness,
    MAX(b.source_workbook) FILTER (WHERE b.concept = 'npm') AS npm_source_workbook,
    MAX(b.conflict_flag::text) FILTER (WHERE b.concept = 'npm') AS npm_conflict,
    MAX(b.value) FILTER (WHERE b.concept = 'cebpa') AS cebpa,
    MAX(b.missingness_class) FILTER (WHERE b.concept = 'cebpa') AS cebpa_missingness,
    MAX(b.source_workbook) FILTER (WHERE b.concept = 'cebpa') AS cebpa_source_workbook,
    MAX(b.conflict_flag::text) FILTER (WHERE b.concept = 'cebpa') AS cebpa_conflict,
    MAX(b.value) FILTER (WHERE b.concept = 'fab') AS fab,
    MAX(b.missingness_class) FILTER (WHERE b.concept = 'fab') AS fab_missingness,
    MAX(b.source_workbook) FILTER (WHERE b.concept = 'fab') AS fab_source_workbook,
    MAX(b.conflict_flag::text) FILTER (WHERE b.concept = 'fab') AS fab_conflict,
    MAX(b.value) FILTER (WHERE b.concept = 'cns_disease') AS cns_disease,
    MAX(b.missingness_class) FILTER (WHERE b.concept = 'cns_disease') AS cns_disease_missingness,
    MAX(b.source_workbook) FILTER (WHERE b.concept = 'cns_disease') AS cns_disease_source_workbook,
    MAX(b.conflict_flag::text) FILTER (WHERE b.concept = 'cns_disease') AS cns_disease_conflict,
    MAX(b.value) FILTER (WHERE b.concept = 'marrow_blasts') AS marrow_blasts,
    MAX(b.missingness_class) FILTER (WHERE b.concept = 'marrow_blasts') AS marrow_blasts_missingness,
    MAX(b.source_workbook) FILTER (WHERE b.concept = 'marrow_blasts') AS marrow_blasts_source_workbook,
    MAX(b.units) FILTER (WHERE b.concept = 'marrow_blasts') AS marrow_blasts_units,
    MAX(b.conflict_flag::text) FILTER (WHERE b.concept = 'marrow_blasts') AS marrow_blasts_conflict,
    MAX(b.value) FILTER (WHERE b.concept = 'peripheral_blasts') AS peripheral_blasts,
    MAX(b.missingness_class) FILTER (WHERE b.concept = 'peripheral_blasts') AS peripheral_blasts_missingness,
    MAX(b.source_workbook) FILTER (WHERE b.concept = 'peripheral_blasts') AS peripheral_blasts_source_workbook,
    MAX(b.units) FILTER (WHERE b.concept = 'peripheral_blasts') AS peripheral_blasts_units,
    MAX(b.conflict_flag::text) FILTER (WHERE b.concept = 'peripheral_blasts') AS peripheral_blasts_conflict,
    MAX(b.value) FILTER (WHERE b.concept = 'cytogenetics_t821') AS cytogenetics_t821,
    MAX(b.missingness_class) FILTER (WHERE b.concept = 'cytogenetics_t821') AS cytogenetics_t821_missingness,
    MAX(b.source_workbook) FILTER (WHERE b.concept = 'cytogenetics_t821') AS cytogenetics_t821_source_workbook,
    MAX(b.conflict_flag::text) FILTER (WHERE b.concept = 'cytogenetics_t821') AS cytogenetics_t821_conflict,
    MAX(b.value) FILTER (WHERE b.concept = 'cytogenetics_inv16') AS cytogenetics_inv16,
    MAX(b.missingness_class) FILTER (WHERE b.concept = 'cytogenetics_inv16') AS cytogenetics_inv16_missingness,
    MAX(b.source_workbook) FILTER (WHERE b.concept = 'cytogenetics_inv16') AS cytogenetics_inv16_source_workbook,
    MAX(b.conflict_flag::text) FILTER (WHERE b.concept = 'cytogenetics_inv16') AS cytogenetics_inv16_conflict,
    MAX(b.value) FILTER (WHERE b.concept = 'cytogenetics_mll') AS cytogenetics_mll,
    MAX(b.missingness_class) FILTER (WHERE b.concept = 'cytogenetics_mll') AS cytogenetics_mll_missingness,
    MAX(b.source_workbook) FILTER (WHERE b.concept = 'cytogenetics_mll') AS cytogenetics_mll_source_workbook,
    MAX(b.conflict_flag::text) FILTER (WHERE b.concept = 'cytogenetics_mll') AS cytogenetics_mll_conflict,
    MAX(b.value) FILTER (WHERE b.concept = 'cytogenetics_monosomy7') AS cytogenetics_monosomy7,
    MAX(b.missingness_class) FILTER (WHERE b.concept = 'cytogenetics_monosomy7') AS cytogenetics_monosomy7_missingness,
    MAX(b.source_workbook) FILTER (WHERE b.concept = 'cytogenetics_monosomy7') AS cytogenetics_monosomy7_source_workbook,
    MAX(b.conflict_flag::text) FILTER (WHERE b.concept = 'cytogenetics_monosomy7') AS cytogenetics_monosomy7_conflict,
    MAX(b.value) FILTER (WHERE b.concept = 'primary_cytogenetic_code') AS primary_cytogenetic_code,
    MAX(b.missingness_class) FILTER (WHERE b.concept = 'primary_cytogenetic_code') AS primary_cytogenetic_code_missingness,
    MAX(b.source_workbook) FILTER (WHERE b.concept = 'primary_cytogenetic_code') AS primary_cytogenetic_code_source_workbook,
    MAX(b.conflict_flag::text) FILTER (WHERE b.concept = 'primary_cytogenetic_code') AS primary_cytogenetic_code_conflict
FROM analytics.primary_os_cohort AS c
LEFT JOIN analytics.baseline_covariates_reconciled AS b
    ON c.analysis_person_id = b.analysis_person_id
GROUP BY
    c.analysis_person_id,
    c.gdc_case_id,
    c.submitter_id,
    c.age_at_diagnosis_days,
    c.age_at_diagnosis_years,
    c.vital_status,
    c.os_event,
    c.os_days,
    c.os_years,
    c.os_time_source,
    c.os_event_source,
    c.identity_rule,
    c.source_provenance,
    c.qa_flags;
